---
title: "useR Demo"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r, include = FALSE}
library(flexdashboard)
```

Page 1
=================================================
    
Row
-------------------------------------
    
### Chart 1
    
```{r}
```
   
Row
-------------------------------------
    
### Chart 2
    
```{r}
```
    
### Chart 3

```{r}
```


Page 2
=================================================
    
Row {.tabset}
-------------------------------------
    
### Chart 1
    
```{r}
```
    
### Chart 2
    
```{r}
```
    
### Chart 3

```{r}
```


Page 3
=================================================

Row
-------------------------------------------------

### Value Box 1

```{r}
flexdashboard::valueBox(paste0(80, "%"), 
         caption = "of people estimated to be newly diagnosed with dementia were referred for post-diagnostic support.")
```

### Value Box 2

```{r}
flexdashboard::valueBox(paste0(80, "%"), icon = "fa-percent",
         caption = "of people estimated to be newly diagnosed with dementia were referred for post-diagnostic support.")
```

Row
-------------------------------------------------

### Gauge 1

```{r}
flexdashboard::gauge(30, symbol = "%", 
                     min = 0, max = 100,
                     gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```

### Gauge 2

```{r}
flexdashboard::gauge(60, symbol = "%", 
                     min = 0, max = 100,
                     gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
  ))
```

### Gauge 3

```{r}
flexdashboard::gauge(80, symbol = "%", 
                     min = 0, max = 100,
                     gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
  ))
```
